language: objective-c
# should give access to macOS 10.14
osx_image: xcode12

script:
  - brew tap colinaaa/hust
  - travis_wait 60 brew install logisim-hust logisim-ita colinaaa/hust/mars
  - brew uninstall logisim-hust logisim-ita colinaaa/hust/mars
