language: objective-c
# should give access to macOS 10.14
osx_image: xcode12

script:
  - brew tap colinaaa/hust
  - travis_wait 60 brew cask install logisim-hust logisim-ita
  - brew cask uninstall logisim-hust logisim-ita
