name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: ["macos-11.0", "macos-10.15"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Tap colinaaa/hust
        run: brew tap colinaaa/hust

      - name: Run brew install
        id: install
        run: brew install --cask logisim-hust logisim-ita colinaaa/hust/mars
        timeout-minutes: 10

      - name: Run brew uninstall
        run: brew uninstall --cask logisim-hust logisim-ita colinaaa/hust/mars
        timeout-minutes: 10
